### ISSUE TITLE
Suggestion feature

### ISSUE THREAD

**Issue by Raynos** [alantech/alan#187]
Useful language features from go / javascript would be 

 - i64
 - bigint
 - some form of struct type thats performant, either mutable or immutable or both. The fact that js has objects with heap allocated integers as fields instead of fixed size structs is ...

**Comment by dfellis** [comment]
Will address piece-by-piece:

1. All integers in Alan are i64 by default. :) (Those the JS runtime can't do that.)
2. Yes, but we can add that relatively easily without impact the language design, so it has been deprioritized.
3. All user types are already like that :) The compiler converts the type properties into memory offsets internally. Only HashMap behaves similarly to JS objects.

**Comment by Raynos** [comment]
Nice. Sensible defaults.
