### ISSUE TITLE
package.json in gitignore

### ISSUE THREAD

**Issue by Raynos** [alantech/alan#190]
Running `yarn add ./compiler` without a package.json does not work locally.

I ran `npm init` and then `make install` works.

I see `package.json` is in gitignore but it's a necessary file for `yarn add` to work.

**Comment by dfellis** [comment]
All we get is a warning about that. :/ What version of `yarn` are you on now?

We can add `npm init` to the Makefile.

**Comment by Raynos** [comment]
```
raynos at raynos-Precision-5530  
~/optoolco/buckets on master
$ yarn -v
1.22.4
```

**Comment by dfellis** [comment]
> ```
> raynos at raynos-Precision-5530  
> ~/optoolco/buckets on master
> $ yarn -v
> 1.22.4
> ```

![what](https://www.reactiongifs.com/r/2013/08/wtf.gif)

**Comment by dfellis** [comment]
It looks like you're on a Linux, and you have the exact same version of yarn as I do, but I only get a warning and you get an error?

**Comment by dfellis** [comment]
I just merged the `Makefile` change that should fix this @Raynos can you pull the latest code and confirm/deny?

**Comment by Raynos** [comment]
```
raynos at raynos-Precision-5530  
~/projects/alan on main
$ alan-runtime run temp.aga 
thread 'main' panicked at 'index out of bounds: the len is 44 but the index is 44', src/vm/program.rs:20:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Yeah I can run `make install`

```
cp ./runtime/target/release/alan-runtime /usr/local/bin/alan-runtime
cp: cannot create regular file '/usr/local/bin/alan-runtime': Permission denied
Makefile:48: recipe for target 'install' failed
make: *** [install] Error 1
```

I got the sudo cp issue and manually copied the `alan-runtime`

I then tried a hello world

```
raynos at raynos-Precision-5530  
~/projects/alan on main
$ cat temp.ln 
import @std/app

on app.start {
  app.print("Hello, World!")
  emit app.exit 0
}
```

Alan runtime was not pleased.

**Comment by dfellis** [comment]
> ```
> raynos at raynos-Precision-5530  
> ~/projects/alan on main
> $ alan-runtime run temp.aga 
> thread 'main' panicked at 'index out of bounds: the len is 44 but the index is 44', src/vm/program.rs:20:18
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> ```
> 
> Yeah I can run `make install`
> 
> ```
> cp ./runtime/target/release/alan-runtime /usr/local/bin/alan-runtime
> cp: cannot create regular file '/usr/local/bin/alan-runtime': Permission denied
> Makefile:48: recipe for target 'install' failed
> make: *** [install] Error 1
> ```
> 
> I got the sudo cp issue and manually copied the `alan-runtime`
> 
> I then tried a hello world
> 
> ```
> raynos at raynos-Precision-5530  
> ~/projects/alan on main
> $ cat temp.ln 
> import @std/app
> 
> on app.start {
>   app.print("Hello, World!")
>   emit app.exit 0
> }
> ```
> 
> Alan runtime was not pleased.

So you need to compile to AGC, not AGA. AGA is the "assembler" version that you can open in a text editor and read, AGC is the actual binary that the runtime can parse and execute.

**Comment by Raynos** [comment]
can you put that in `alan-runtime`

```
if (file.endsWith('.aga')) {
  console.warn('.aga files are assembler, please use .agc file instead')
  process.exit(1)
}
```

**Comment by dfellis** [comment]
Well, nothing on the website talks about `aga` at all, yet. How did you come across it?

**Comment by Raynos** [comment]
```
To compile to Alan's second intermediate representation, alan graphcode assembler:

alan-compile <source>.ln <whateveryouwant>.aga
```

I did `cat README.md` and scrolled upwards until I saw the first `alan-compile` example without reading the rest of the README

**Comment by Raynos** [comment]
i just assumed that your compiler would not change the output based on the file extension

**Comment by Raynos** [comment]
like I thought `alan-compile foo.ln a.out` would work too

**Comment by dfellis** [comment]
Ohh, yes, we mention it in the source code repository, but intentionally left it off of the [Getting Started](https://docs.alan-lang.org/) page.

I am curious how we can handle this better, though? (Especially since you searched the README backwards).

As for the output changing based on the extension, that's because the compiler is also a transpiler to JS, and it was just simpler to have the compiler figure out what you need based on the file you're trying to generate.

**Comment by Raynos** [comment]
there's not really much for it, i should have run `alan-compile -h` instead.

**Comment by dfellis** [comment]
> there's not really much for it, i should have run `alan-compile -h` instead.

Well, that's actually pretty bare, too, right now. Let me beef that up.

**Comment by dfellis** [comment]
@Raynos does this look better? https://github.com/alantech/alan/pull/231

**Comment by Raynos** [comment]
Yes. There’s more stuff.

**Comment by dfellis** [comment]
Is it good stuff? :)
