### ISSUE TITLE
Write a syntax highlighter for the browser

### ISSUE THREAD

**Issue by dfellis** [alantech/alan#221]
Implement in [highlightjs](https://github.com/highlightjs/highlight.js/blob/master/SUPPORTED_LANGUAGES.md) which is what the mdbook uses. The homepage and docs are both built on mdbook.

**Comment by depombo** [comment]
https://highlightjs.readthedocs.io/en/latest/language-requests.html

**Comment by depombo** [comment]
The ace editor used in the playground will need it's own syntax highlighting as well

**Comment by dfellis** [comment]
> The ace editor used in the playground will need it's own syntax highlighting as well

![oh no](https://media.juiceonline.com/wp-content/uploads/2018/01/17172725/Alex-Norris-Webcomic-Name-comics-12-1024x609.jpg)

**Comment by jcorbin** [comment]
It looks like Ace is descended from TextMate, and isn't that also what vscode uses for its definitions? Maybe eventually there's some advantage to a native ace definition, but it looks like they have a tool for consuming a textmate grammar?

**Comment by jcorbin** [comment]
Yeah, so you have a "tmLanguage" json file: https://github.com/alantech/vscode-alan/blob/main/syntaxes/alan.tmLanguage.json ; which ace has a tool for according to https://ace.c9.io/#nav=higlighter

**Comment by dfellis** [comment]
> Yeah, so you have a "tmLanguage" json file: https://github.com/alantech/vscode-alan/blob/main/syntaxes/alan.tmLanguage.json ; which ace has a tool for according to https://ace.c9.io/#nav=higlighter

Thank you so much for pointing us at that! That'll save us a few hours of headaches we would've run into otherwise. :)

**Comment by depombo** [comment]
This is awesome, thank you so much @jcorbin :)

**Comment by depombo** [comment]
Ace: https://github.com/alantech/homepage/pull/50, https://github.com/alantech/docs/pull/35
HighlightJS: https://github.com/alantech/highlightjs-alan, https://github.com/alantech/homepage/pull/53, https://github.com/alantech/docs/pull/36
