### ISSUE TITLE
alan-runtime run with an non existing file panics on a unwrap instead of an error message

### ISSUE THREAD

**Issue by LoPoHa** [alantech/alan#249]
If the alan-runtime gets called with a file that doesn't exist it unwraps (src\vm\run.rs:98:32)
I'm not sure how you want such errors to be handled so i didn't create a pr.
But something simple like .expect("The given file was not found") would be better than the unwrap here.

**Comment by dfellis** [comment]
Absolutely something we should tackle! We have a [test just for compiler errors](https://github.com/alantech/alan/blob/main/bdd/spec/019_compiler_error_spec.sh), we should make a similar one for runtime errors.
