### ISSUE TITLE
Compilation error parsing `app.print(2 / (3))`

### ISSUE THREAD

**Issue by ogier** [alantech/alan#251]
How to reproduce:

1. Visit alan-lang.com.
2. Replace "Hello, World!" with `2 / (3)`.
3. Execute code snippet.

Result:

```
Cannot read property 'basicassignables' of null
```

**Comment by dfellis** [comment]
Hi @ogier thank you for reporting this. I can confirm that if you put `2 / (1 + 2)` in there it *does* work, so I think I know what's going on here. :)
