### ISSUE TITLE
"Get Started" button should be a link

### ISSUE THREAD

**Issue by ogier** [alantech/alan#252]
On the homepage, the "Get Started" button is a clickable `<button>` element with a javascript onclick action that updates the page's URL. This prevents normal things like clicking with the middle mouse button to open in a new tab, and presumably it does nothing at all if the user has JavaScript disabled (though I didn't test this). This should be a proper link styled like a button rather than a button with a javascript handler.

**Comment by dfellis** [comment]
Hi again @ogier 

You are absolutely right. I know how this happened, too. Originally the "Get Started" button was another "Run code" button, then we changed its behavior but didn't update the HTML implementation of it.

I'm going to create an issue on https://github.com/alantech/homepage referencing this one and then close this one out.
