### ISSUE TITLE
Write RFC for how to do JSON serialization and parse

### ISSUE THREAD

**Issue by dfellis** [alantech/alan#278]

**Comment by LoPoHa** [comment]
It would be nice if the serialization/deserialization would be somewhat generic, to allow for serialization to other formats (protobuf, flatbuffers, messagepack, ...) and the json one build upon the generic one.
Some other languages allow code to be executed at compile time, accessing and modifying the ast.
This would be somewhat related to #218

**Comment by dfellis** [comment]
That's why this task is taking me so long. :)

I want to do this in a generic-enough way that I can immediately start putting it to work on rewriting the compiler in Alan, probably one layer at a time.

**Comment by dfellis** [comment]
As for compile-time modification, I had some ideas written down for that, too, but I have lost them. I understand the perils of going full LISP/Perl6 on this and letting developers produce wildly different languages within your language that kills legibility of the ecosystem as a whole, but macros are very powerful and useful.

The gist of that idea was to create macro functions that take constants only as arguments (or perhaps other macro functions) and the internals of a macro function is a module scope that must export a single value, where that value is implicitly imported and used wherever the macro function is called. I think it provided a useful level of compile-time power without allowing new syntax generation, but I'm afraid I'm gonna have to rewrite it.

**Comment by dfellis** [comment]
We're just implementing JSON serialization and parse in pure Alan, so no RFC (also already mostly done)
