### ISSUE TITLE
User defined type can't be used inside start event

### ISSUE THREAD

**Issue by LoPoHa** [alantech/alan#281]
Trying to use a user defined type results in an "XXX not yet supported" error.

The following works without problems:
```
from @std/app import start, exit

type Test {
  owner: bool
}

const test = new Test {
  owner: true
}

on start {
  emit exit 0
}
```
---

But trying to instance Test inside start:

```
from @std/app import start, exit

type Test {
  owner: bool
}

on start {
  const test = new Test {
    owner: true
  }

  emit exit 0
}
```

Results in the following error:
```
Test not yet supported
new Test {
    owner: true
  } on line 2:23
```

---

The same happens if test is instantiated outside of start, but is used as an input to a function:

```
from @std/app import start, exit

type Test {
  owner: bool
}

const test = new Test {
  owner: true
}

fn giveString(test: Test) : string {
  if test.owner {
    return "Ok"
  } else {
    return "Not Ok"
  }
}

on start {
  giveString(test).print()
  emit exit 0
}
```

```
Test not yet supported
new Test {
  owner: true
} on line 7:13
```

---

OS: Windows 10
```
> alan --version
alan 0.1.8
```

**Comment by dfellis** [comment]
Hi @LoPoHa :)

So your first example should have failed as well, and I need to figure out why that one didn't error on you (perhaps because that constant wasn't used so it simply ignored it entirely and never triggered the error?)

The issue is the way you're assigning the values in the object. It should look like:

```
from @std/app import start, exit

type Test {
  owner: bool
}

on start {
  const test = new Test {
    owner = true
  }

  emit exit 0
}
```

An equal sign instead of a colon inside of the object.

Confirmation that that's the issue here:

```
damocles@Talyn:/usr/local/alancorp/alan(main)$ cat test.ln
from @std/app import start, exit

type Test {
  owner: bool
}

on start {
  const test = new Test {
    owner = true
  }

  emit exit 0
}
damocles@Talyn:/usr/local/alancorp/alan(main)$ alan compile test.ln test.js
Done in 6.494s
```

The reason why it's saying "not yet supported" is because the colon syntax is intended to be used for HashMaps, so you can do something like:

```
new HashMap<bool, string> {
  true: "correct"
  false: "wrong"
}
```

I should add a better error message if the type isn't a HashMap, though.

Also debating whether or not to have the two syntaxes at all and just follow Javascript's style here, despite it making the parsing a bit more complicated.

**Comment by LoPoHa** [comment]
Ah, ok.
But yeah, the error message is a bit confusing here :)

Btw. another confusing error is if you use `event` instead of the event name.
I think it expects a new event declaration here:
```
line 11:3 extraneous input 'event' expecting {BOOLCONSTANT, '(', '[', '.', NEWLINE, WS, STRINGCONSTANT, NUMBERCONSTANT, VARNAME}
Could not find specified event:
```

I think this could also be clarified (when the compiler is rewritten in alan)
Until then i'll wait with issues on confusing error messages.

On the syntax side, i normally favor if there is only one way to do things.
It makes reading it easier (imo) and doesn't raise the question: you support x number of syntax sugars for the same thing, why not support another one having x+1?
But that's for you to decide 😄

**Comment by dfellis** [comment]
> Ah, ok.
> But yeah, the error message is a bit confusing here :)
> 
> Btw. another confusing error is if you use `event` instead of the event name.
> I think it expects a new event declaration here:
> 
> ```
> line 11:3 extraneous input 'event' expecting {BOOLCONSTANT, '(', '[', '.', NEWLINE, WS, STRINGCONSTANT, NUMBERCONSTANT, VARNAME}
> Could not find specified event:
> ```
> 
> I think this could also be clarified (when the compiler is rewritten in alan)
> Until then i'll wait with issues on confusing error messages.
> 
> On the syntax side, i normally favor if there is only one way to do things.
> It makes reading it easier (imo) and doesn't raise the question: you support x number of syntax sugars for the same thing, why not support another one having x+1?
> But that's for you to decide smile

Curious which syntax you feel is the `x+1` here. :) Assignment using equal signs technically makes the current syntax in Alan have less weirdness to memorize than allowing colons to be used for type declarations, but it is a new syntax versus what most people have already learned.
