### ISSUE TITLE
import lines should not complain about trailing spaces while parsing

### ISSUE THREAD

**Issue by LoPoHa** [alantech/alan#282]
main.ln

```
from @std/app import start, print, exit
from ./piece import Piece 

on start {
  const piece = new Piece {
    owner = false
  }
  print("Hello World")
  if piece.owner == true {
    print("OK")
  } else {
    print("False")
  }
  emit exit 0
}
```

piece.ln

```
type Piece {
  owner: bool
}
```

Result:
```
> alan compile .\asahi.ln .\asahi.agc && alan run .\asahi.agc
Done in 6.354s
line 3:26 mismatched input '\r\n' expecting 'as'
Hello World
False
```

**Comment by dfellis** [comment]
So I know what is causing that extraneous input error from ANTLR: You must have an extra space at the end of one of the import lines. Despite the weird printing order you see, that warning came from the compiler, not running the code. If you run your AGC file again you can confirm for yourself. :)

On another note, did you really not export the `Piece` type? You aren't supposed to be able to import anything that wasn't explicitly exported. It's nearly midnight here, but I will be digging into that in the morning.

**Comment by LoPoHa** [comment]
Oh, i knew that it was a compiler error, but wanted to show that it runs correctly.
I just confirmed that it is an extra whitespace after Piece 👍

Yes, i don't export it.
I added export to piece, but it didn't fix the error.
So i deemed it unnecessary atm.
I'll create a new issue for it.

**Comment by dfellis** [comment]
Since the issue was split, I'm gonna rename this issue to focus on the warning from the ANTLR grammar.
