### ISSUE TITLE
Make does not work

### ISSUE THREAD

**Issue by grd** [alantech/alan#284]
Hi. I am really interested in this new PL but I can't install. The OS that I use is Ubuntu 20.04 LTS and the install is pretty standard with most of it working. Make complains about the version of node.js which should be >=10.20.1 but the standard Ubuntu 20.04 LTS is installed with node.js version 10.19. So it doesn't install.

**Comment by grd** [comment]
So I installed node.js with the following commands:
```
# Using Ubuntu
curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
sudo apt-get install -y nodejs
```
And the output of 'node -v' reports v10.22.1 which is the right version ... but still 'make' complains that the node.js version should be >= 10.20.1.

**Comment by grd** [comment]
it's compiling

**Comment by dfellis** [comment]
Good morning. What did you do to get it working? Was the old node still on the PATH?

**Comment by grd** [comment]
No. Unfortunately I had to reinstall the OS. But that is okay since it was bloated anyway.

**Comment by dfellis** [comment]
Sorry to hear that. :/ But glad you seem somewhat pleased with the overall result?
