### ISSUE TITLE
Revive IO parallelization within a Handler

### ISSUE THREAD

**Issue by dfellis** [alantech/alan#303]
Depends on #197 to be fixed. Had to turn it off because now with the closure-accepting opcodes being converted into IO opcodes for scheduling purposes, running them in parallel without the proper dependency declarations means that they don't work correctly.

**Comment by depombo** [comment]
Might still not fully work for certain edge cases given https://github.com/alantech/alan/issues/331

**Comment by depombo** [comment]
Resolved by https://github.com/alantech/alan/pull/336
