### ISSUE TITLE
Exporting an assignment statement does not halt in AGC mode

### ISSUE THREAD

**Issue by MareinK** [alantech/alan#327]
`test.ln`:
```
import @std/app

export x = 1

on app.start {
    emit app.exit 0
}
```
Run `alan compile test.ln test.agc`. Then, running `alan run test.agc` seems to take forever.

It does halt with `alan compile test.ln test.js` then `node test.js`.

**Comment by dfellis** [comment]
I am surprised the compiler didn't error on that. That's an assignment without an initial declaration. `export const x = 1` should work correctly and this should have been a compiler error.

**Comment by dfellis** [comment]
This has been fixed for a while and I didn't notice.

```
alan compile temp.ln temp.amm
Could not load /usr/local/alancorp/alan/temp.ln
AST Parse error, cannot continue due to syntax error between line 3:10 - 6:7
```

Likely when we switched from ANTLR to our homegrown parser.
