### ISSUE TITLE
Multiple problems with the AVM and multiply-nested array method calls

### ISSUE THREAD

**Issue by dfellis** [alantech/alan#343]
The AVM currently eager schedules parallel array operations, which creates a fork of the handler memory space so they can safely run in parallel.
With a large enough number of arrays this can OOM the AVM even though only up to `n` (cpu core count) instances can run at a time. Slowing this down and tossing up batches of elements to process at a time should help here.

Relatedly, explicitly using a linear version of these array methods runs slower than the JS transpiled version of the Alan code. This has to be an issue with how the Tokio tasks are scheduled in the AVM right now and causing a lot of unnecessary overhead. Reusing the existing Tokio thread for the iterations in the linear form should be used, instead.

Hat tip to @ledwards for pointing this out.

**Comment by depombo** [comment]
> The AVM currently eager schedules parallel array operations, which creates a fork of the handler memory space so they can safely run in parallel.
> With a large enough number of arrays this can OOM the AVM even though only up to `n` (cpu core count) instances can run at a time. Slowing this down and tossing up batches of elements to process at a time should help here.
WIll be fixed by https://github.com/alantech/alan/issues/354

> Relatedly, explicitly using a linear version of these array methods runs slower than the JS transpiled version of the Alan code. This has to be an issue with how the Tokio tasks are scheduled in the AVM right now and causing a lot of unnecessary overhead. Reusing the existing Tokio thread for the iterations in the linear form should be used, instead.
> 
Fixed by https://github.com/alantech/alan/pull/346

**Comment by depombo** [comment]
https://github.com/alantech/alan/pull/384 and https://github.com/alantech/alan/pull/374 allow multiply nested array methods to work and have decent performance which is why I closed this out. It is worth pointing out tossing up batches of elements, which is called out in the description is still not done, but is not necessary to fix the bug and will be tracked in https://github.com/alantech/alan/issues/354
