### ISSUE TITLE
Two minor remarks

### ISSUE THREAD

**Issue by Ivo-Balbaert** [alantech/alan#362]
1) You changed 
 “ Remove reference to Python2 now that it is no longer needed for build “ on the docs\getting_started page

You should also remove it in the readme.md on this main GitHub page: alantech/alan: The Alan Programming Language (github.com) 

(seems to little to make a PR for it, but if you want I can do it)

2) The help text given by alan -h:
alan -h
alan 0.1.23
The Alan Compiler and VM

USAGE:
    alan [SOURCE] [SUBCOMMAND]
….
← this should be: alan [SUBCOMMAND] [SOURCE] 

Great project, I love it!

**Comment by dfellis** [comment]
I will definitely fix (1). However (2) is actually correct. The brackets `[]` indicate an optional element, so you can either call `alan subcommand ...` or `alan sourcefile.ln` directly. The latter form tries to imitate dynamic languages by compiling the source file, executing it, and then deleting the intermediate representation after running.

We hope to get the compiler fast enough that Alan could be used in scripting language contexts, too. :)

**Comment by dfellis** [comment]
(Also, those usage docs are autogenerated, so we can't change them.)

**Comment by Ivo-Balbaert** [comment]
Ok thanks, now I understand, I was a bit confused by it.
