### ISSUE TITLE
Automatically unwrap Result and Maybe within the an is_ok / is_some / is_err conditional check

### ISSUE THREAD

**Issue by depombo** [alantech/alan#372]
it would be important to introduce this early on because it will be different behavior to Rust even if the solution is not great at first. We could also sidestep complex boolean logic for the first version of it so that it only works when checked individually:
```
if myVal.isOk() {
  processPayment(myVal.getOrExit());
} else { ...
```
can then simply be:
```
if myVal.isOk() {
  processPayment(myVal);
} else { ...
```

**Comment by dfellis** [comment]
This is now tracked with #414
