### ISSUE TITLE
Broken "runnable examples" link in README.md

### ISSUE THREAD

**Issue by themaxdavitt** [alantech/alan#422]
The "runnable examples" link in `README.md` points to `https://docs.alan-lang.org/advanced_examples.html` when I _think_ (I'm new to this project) it should point to `https://docs.alan-lang.org/examples.html`.

**Comment by depombo** [comment]
@themaxdavitt you are absolutely right! Thank you for pointing that out. Fixing it with https://github.com/alantech/alan/pull/423. Let us know if you have any questions :)

**Comment by themaxdavitt** [comment]
No problem and will do! 👍
