### ISSUE TITLE
Generic Functions

### ISSUE THREAD

**Issue by cdmistman** [alantech/alan#529]
There should be a conversation on how to design generic type variable declarations, as the current system of "all `any` types are the same type variable" would require complex, hard-coded recognition in the LNN compiler that probably won't be easy to replace in the future. An incomplete list of designs to be considered:
- `fn do<T: any>(t: T): T { ... }`
- `fn do[T: any](t: T): T { ... }`
- `fn do{T: any}(t: T): T { ... }`
- `fn do(T: any, t: T): T { ... }`
  - This would require passing the type into the call, eg `do(string, "hello, world!")`
- `fn do(T: any)(t: T): T { ... }`
  - This can be implemented similar to D's templated function calling, eg `do!string("hello, world!")`
  - Can also be done with `do(string)("hello, world!")`
- `fn do(t: T): T with T: any { ... }`
  - This is inspired by Rust's `where` clauses, and in fact `where` could be used instead
  - Function calling would be mostly inferred - which isn't impossible, but there should still be a way to determine if the selected types are potentially wrong. This will work similarly to what @dfellis comments on below
    - Note that trying to assign type variables to an interface type isn't allowed, even if the interface is a subset of the type parameter's interface constraint. For example, an interface `interface Printable { toString(Printable): string; goPrint(Printable); }` cannot be used when calling `fn print(val: T) with T: Stringifiable` could not be called with the alternative calling syntax `print<Printable>(someVal)` (given `someVal` is some type that implements `Printable`)

### Status
- We still must decide on the design for this

**Comment by dfellis** [comment]
For completeness, the current compiler accomplishes this with interface type aliasing:

```ln
fn do(t: any): any { ... }
```

Where both `any`s are implicitly referring to the same internal type, while something like

```ln
type anythingElse = any;
fn do(t: any): anythingElse { ... }
```

has the same interface constraints on the type but doesn't have the further constraint that they are both actually the same type under the hood.

The advantage is the lack of an extra syntax for users to learn. The "complex, hard-coded recognition" is not complex at all. You're simply looking at the input and output types of the function signature and if any of them have a matching interface name, they act like the `<T: interface>` constraint where the generic type just happens to have the same name. It's just a simple loop over the input signature and the LNN data structures under the hood could treat it like the generic type declaration as defined above.

This syntax *does* have a downside, though, to be fair: you can't define a generic type that isn't one of the input or output types of the function signature, which makes constructor functions complicated. For instance,

```ln
const myHashMap = newHashMap('foo', 5);
```

the `newHashMap` constructor *requires* the first value defined. You can't make a proper hashmap object without any keys set at the moment. That could be resolved with something like:

```ln
const myHashMap = newHashMap<string, int64>();
```

but this also regresses (in a way) the automatic type inference we want for Alan.

Something like:

```ln
const myHashMap = newHashMap();
// Potentially a lot of code in between
myHashMap.set('foo', 5);
```

would get us back to that, but how to get *that* working seems complicated. How would that be declared, can you still use an explicitly-typed syntax, can we infer based on arguments to a function that used the type in tandem?
